CREATE TABLE students (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(100) NOT NULL, email varchar(150), age integer);
CREATE TABLE courses (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, course_name varchar(100) NOT NULL, teacher varchar(100));
CREATE TABLE enrollments (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id integer REFERENCES students(id), course_id integer REFERENCES courses(id), grade integer CHECK (grade BETWEEN 0 AND 100));
INSERT INTO students(name,email,age) VALUES ('Alice Chan','alice@example.com',18),('Bob Wong','bob@example.com',19),('Charlie Lee','charlie@example.com',18),('Diana Ho','diana@example.com',20),('Eric Lam','eric@example.com',19),('Fiona Cheung','fiona@example.com',18);
INSERT INTO courses(course_name,teacher) VALUES ('Database Fundamentals','Mr Chan'),('Web Development','Ms Lee'),('Python Programming','Mr Wong'),('Computer Science','Ms Ho');
INSERT INTO enrollments(student_id,course_id,grade) VALUES (1,1,88),(1,2,92),(2,1,75),(2,3,81),(3,1,95),(3,2,87),(3,3,91),(4,2,78),(4,4,85),(5,1,84),(5,3,89),(6,1,93),(6,4,90);
